spring.application.name=JPA

#DB or DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres_pwd
spring.datasource.url=jdbc:postgresql://localhost:1300/spring_db


#JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true